import Header from "@/components/Header"
import './index.css'
import Footer from "@/components/Footer"

export const metadata = {
  title: {
    absolute: "",
    default: "Sample",
    template: "%s | Explore Nextjs",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">

        <Header />
        <div className="p-6 ">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
